name: download cuda libraries
description: cuda libraryをダウンロードする
inputs:
  cudnn_download_url:
    description: cudnnのダウンロードURL
    required: true
  asset_name:
    description: assetの名前
    required: true
  cuda_version:
    description: cudaのバージョン
    required: true
  extract_dir:
    description: 出力先のディレクトリ
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare CUDA cache
      uses: actions/cache@v2
      id: cuda-library-cache
      with:
        key: v1-cuda-library-cache-${{ inputs.asset_name }}-${{ inputs.cuda_version }}
        path: download/cuda
    - name: Prepare cuDNN cache
      uses: actions/cache@v2
      id: cudnn-library-cache
      with:
        key: v1-cudnn-library-cache-${{ inputs.asset_name }}-${{ inputs.cudnn_download_url }}
        path: download/cudnn
    - name: Extract CUDNN Library
      if: steps.cudnn-library-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -eux
        mkdir -p download/cudnn_tmp
        if [[ "${{ runner.os }}" = "Linux" ]]; then
          curl -L "${{ inputs.cudnn_download_url }}" > download/cudnn.tar.xz
          tar -Jxvf download/cudnn.tar.xz -C download/cudnn_tmp
          mkdir -p download/cudnn_tmp/bin
          # このディレクトリはcudnnのバージョンによって変わってしまうことがあるので注意すること
          mv -v download/cudnn_tmp/**/lib/* download/cudnn_tmp/bin
        elif [[ "${{ runner.os }}" = "Windows" ]];then
          curl -L "${{ inputs.cudnn_download_url }}" > download/cudnn.zip
          unzip download/cudnn.zip cudnn*/bin/*.dll -d download/cudnn_tmp
          mkdir -p ./download/cudnn_tmp/bin
          # このディレクトリはcudnnのバージョンによって変わってしまうことがあるので注意すること
          mv -v ./download/cudnn_tmp/cudnn*/bin/* ./download/cudnn_tmp/bin
        fi
        mkdir -p download/cudnn/bin
        mv download/cudnn_tmp/bin/*.{so*,dll} download/cudnn/bin/ || true
        rm -rf download/cudnn_tmp
        rm -f download/cudnn.*
        mkdir -p ${{ inputs.extract_dir }}
        cp -v docs/licenses/cuda/* "${{ inputs.extract_dir }}"
    - uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        method: network
        cuda: ${{ inputs.cuda_version }}
    - name: Extract CUDA Library
      if: steps.cuda-library-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -eux
        CUDA_ROOT=$( echo "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}" | tr '\\' '/' )
        mkdir -p download/cuda/bin
        if [[ "${{ runner.os }}" = "Linux" ]]; then
          cp -v "$CUDA_ROOT/lib64/"*.so* download/cuda/bin/
        elif [[ "${{ runner.os }}" = "Windows" ]];then
          cp -v "$CUDA_ROOT/bin/"*.dll download/cuda/bin/
        fi
    - name: Extract Libraries for Windows
      shell: bash
      if: ${{ runner.os == 'Windows' }}
      run: |
        # CUDA
        ln -sf "$(pwd)/download/cuda/bin"/cublas64_*.dll "${{ inputs.extract_dir }}"
        ln -sf "$(pwd)/download/cuda/bin"/cublasLt64_*.dll "${{ inputs.extract_dir }}"
        ln -sf "$(pwd)/download/cuda/bin"/cudart64_*.dll "${{ inputs.extract_dir }}"
        ln -sf "$(pwd)/download/cuda/bin"/cufft64_*.dll "${{ inputs.extract_dir }}"
        ln -sf "$(pwd)/download/cuda/bin"/curand64_*.dll "${{ inputs.extract_dir }}"
        # cuDNN
        ln -sf "$(pwd)/download/cudnn/bin"/cudnn64_*.dll "${{ inputs.extract_dir }}"
        ln -sf "$(pwd)/download/cudnn/bin"/cudnn_*_infer64*.dll "${{ inputs.extract_dir }}"
    - name: Extract Libraries for Linux
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        # CUDA
        ln -sf "$(pwd)/download/cuda/bin"/libcublas.so.* "${{ inputs.extract_dir }}"
        rm -f "${{ inputs.extract_dir }}"/libcublas.so.*.*
        ln -sf "$(pwd)/download/cuda/bin"/libcublasLt.so.* "${{ inputs.extract_dir }}"
        rm -f "${{ inputs.extract_dir }}"/libcublasLt.so.*.*
        ln -sf "$(pwd)/download/cuda/bin"/libcudart.so.* "${{ inputs.extract_dir }}"
        rm -f "${{ inputs.extract_dir }}"/libcudart.so.*.*
        ln -sf "$(pwd)/download/cuda/bin"/libcufft.so.* "${{ inputs.extract_dir }}"
        rm -f "${{ inputs.extract_dir }}"/libcufft.so.*.*
        ln -sf "$(pwd)/download/cuda/bin"/libcurand.so.* "${{ inputs.extract_dir }}"
        rm -f "${{ inputs.extract_dir }}"/libcurand.so.*.*
        # cuDNN
        ln -sf "$(pwd)/download/cudnn/bin"/libcudnn.so.* "${{ inputs.extract_dir }}"
        rm -f "${{ inputs.extract_dir }}"/libcudnn.so.*.*
        ln -sf "$(pwd)/download/cudnn/bin"/libcudnn_*_infer.so.* "${{ inputs.extract_dir }}"
        rm -f "${{ inputs.extract_dir }}"/libcudnn_*_infer.so.*.*
